### 주선자용 회원 가입
## provider 는 test 고정이다.
POST http://{{host}}/api/v1/auth/login/test
Content-Type: application/json

{
  "provider": "apple"
}

> {%
    client.test("SignIn Or Login", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
        client.assert(response.body.payload.accessToken.length > 0); // 토큰 길이가 0보다 크면 통과
    });

    client.log(response.body.payload.accessToken);
    client.global.set("refresher_accessToken", response.body.payload.accessToken)
    client.global.set("refresher_refreshToken", response.body.payload.refreshToken)
%}

### 리프레시 토큰 확인
POST http://{{host}}/api/v1/auth/login/refresh
Content-Type: application/json
Authorization: Bearer {{refresher_accessToken}}
X-Refresh-Token: {{refresher_refreshToken}}

{
}

> {%
    client.test("SignIn Or Login", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
        client.assert(response.body.payload.accessToken.length > 0); // 토큰 길이가 0보다 크면 통과
    });

    client.log(response.body.payload.accessToken);
    client.log(response.body.payload.refreshToken);
%}
