### 후보자 프로필 업데이트
POST http://{{host}}/api/v1/candidates
Content-Type: application/json
Authorization: Bearer {{candidate_accessToken}}

{
  "images": {
    "images": [
      {
        "imageUrl": "https://cataas.com/cat",
        "profileOrder": 1
      },
      {
        "imageUrl": "https://cataas.com/cat",
        "profileOrder": 1
      }
    ]
  },
  "gender": "MALE",
  "height": 180,
  "idealAgeRange": [
    "EQUAL",
    "LOWER",
    "OLDER"
  ],
  "idealHeightRange": [
    "HEIGHT_150",
    "HEIGHT_190"
  ],
  "idealMbti": "INTJ",
  "job": "개발자",
  "mbti": "INTJ",
  "city": "서울특별시",
  "district": "강남구",
  "yearOfBirth": 1990,
  "phoneNumber": "010-1234-5678",
  "hobbies": [
    "노래 부르기", "그림 그리기", "운동"
  ],
  "smoke": 1,
  "drink": 1
}

### 후보자 프로필 조회
GET http://{{host}}/api/v1/candidates/profile
Content-Type: application/json
Authorization: Bearer {{candidate_accessToken}}
