### 내가 등록한 후보자 개수 반환
GET http://{{host}}/api/v1/makers/candidates/count
Content-Type: application/json
Authorization: Bearer {{maker_accessToken}}

### 내가 등록하지 않은 후보자 개수 반환
GET http://{{host}}/api/v1/makers/candidates/others/count
Content-Type: application/json
Authorization: Bearer {{maker_accessToken}}

### 내가 등록한 후보자 정보
GET http://{{host}}/api/v1/makers/candidates
Content-Type: application/json
Authorization: Bearer {{maker_accessToken}}

### 내가 등록하지 않은 후보자 정보
GET http://{{host}}/api/v1/makers/candidates/others
Content-Type: application/json
Authorization: Bearer {{maker_accessToken}}
