### Get all arrangements
GET http://{{host}}/api/v1/arrangements/candidates?targetId=1
Content-Type: application/json
Authorization: Bearer {{matchmaker_accessToken}}

### 주선 요청하기
POST http://localhost:8080/api/v1/arrangements
Content-Type: application/json
Authorization: Bearer {{matchmaker_accessToken}}

{
  "leftCandidateId": 3,
  "rightCandidateId": 5
}

### 후보자1 주선 승락하기
POST http://localhost:8080/api/v1/arrangements/1
Content-Type: application/json
Authorization: Bearer {{candidate_accessToken}}

{
  "isAccepted": true
}

### 후보자2 주선 승락하기
POST http://localhost:8080/api/v1/arrangements/1
Content-Type: application/json
Authorization: Bearer {{candidate_accessToken}}

{
  "isAccepted": true
}
