### 내가 등록한 후보자 개수 반환
POST http://{{host}}/api/v1/candidates
Content-Type: application/json
Authorization: Bearer {{candidate_access_token}}

{
  "name": "후보자 실명",
  "email": "후보자 이메일",
  "gender": "MALE",
  "height": 180,
  "idealAgeRange": [
    "EQUAL",
    "LOWER",
    "OLDER"
  ],
  "idealHeightRange": [
    "HEIGHT_150",
    "HEIGHT_190"
  ],
  "idealMbti": "INTJ",
  "job": "개발자",
  "mbti": "INTJ",
  "station": "역삼역",
  "yearOfBirth": 1990,
  "phoneNumber": "010-1234-5678"
}

###
GET http://localhost:8080/api/v1/candidates/profile
Content-Type: application/json
Authorization: Bearer {{candidate_access_token}}
